export const ADD_PRAYER = 'ADD_PRAYER';
export const TOGGLE_PRAYER = 'TOGGLE_PRAYER';
export const REMOVE_PRAYER = 'REMOVE_PRAYER';
export const EDIT_PRAYER = 'EDIT_PRAYER';
export const UPDATE_PRAYER = 'UPDATE_PRAYER';
export const ERROR = 'ERROR';

export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const ACTIVE_COUPON = 'ACTIVE_COUPON';
export const COUPON_EXPIRE = 'COUPON_EXPIRE';
export const UPDATE_BOOKMARK = 'UPDATE_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
export const SELECT_BOOKMARK = 'SELECT_BOOKMARK';
export const USER_SUBSCRIBED = 'USER_SUBSCRIBED';
export const ALREADY_BOOKMARKED = 'ALREADY_BOOKMARKED';
export const REMOVE_ALL_BOOKMARK = 'REMOVE_ALL_BOOKMARK';
export const UPDATE_SELECTED_BOOKMARK = 'UPDATE_SELECTED_BOOKMARK';
export const ALREADY_BOOKMARKED_SUCCESS = 'ALREADY_BOOKMARKED_SUCCESS';
