buildscript {
    ext {
        googlePlayServicesVersion = "+"
        firebaseMessagingVersion = "21.1.0"
        buildToolsVersion = "30.0.0"
        minSdkVersion = 24
        compileSdkVersion = 34
        targetSdkVersion = 35
        ndkVersion = "21.3.6528147"
        kotlin_version = '1.8.0'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.4.2")
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.6'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        maven { url 'https://www.jitpack.io' }
    }

    // ✅ Add this block to force SoLoader 0.10.4+ and REMOVER AFTER UPGRADING REACT NATIVE BEYOND 0.71.8
    configurations.all {
        resolutionStrategy {
            force 'com.facebook.soloader:soloader:0.10.4'
            force 'com.facebook.soloader:annotation:0.10.4'
            force 'com.facebook.soloader:nativeloader:0.10.4'
        }
    }
}
